# windows executable in comand prompt: g++ main.cpp -o main

longDistantCallCalculator: main.cpp
	g++ -o longDistantCallCalculator main.cpp

run:
	./longDistantCallCalculator

clean:
	rm -f longDistantCallCalculator.exe main.exe longDistantCallCalculator main
	
edit:
	vim main.c
